from PIL import Image
import os

def convert_image(name):
    img = Image.open(f"assets/{name}.png").convert("RGBA")

    img_arr = []

    for i in range(img.size[1]):
        row = []
        for j in range(img.size[0]):
            r, g, b, a = img.getpixel((j, i))
            if a == 0:
                row.append(-1)
            elif r == 0 and g == 0 and b == 0:
                row.append(1)
            else:
                row.append(0)
        img_arr.append(row)

    import_text = [
        f"    function Array {name}() " + "{",
        f"        var Array {name};",
        f"        var Array {", ".join([f"{name}_row{i}" for i in range(len(img_arr))])};", # defining rows
        f"        let {name} = Array.new({img.size[1]});"
    ]

    for row in range(len(img_arr)):
        import_text.append(f"        let {name}_row{row} = Array.new({img.size[0]});")
        import_text.append("        ")
        for col in range(len(img_arr[row])):
            import_text[-1] += f'let {name}_row{row}[{col}] = {img_arr[row][col]}; '

    import_text.append("        ")

    for row in range(len(img_arr)):
        import_text[-1] += f"let {name}[{row}] = {name}_row{row}; "

    import_text.append("        return " + name + ";")
    import_text.append("    }")

    return "\n".join(import_text)

file_text = """// generated by compile_images.py
// this file just holds all the assets

// 0 = white
// 1 = black
// -1 = transparent

class Graphics {"""

files = os.listdir("assets")
for file in files:
    if file.endswith(".png"):
        file_text += "\n\n"
        file_text += convert_image(file.replace(".png", ""))

file_text += "\n}"

with open("Graphics.jack", "w") as f:
    f.write(file_text)