from PIL import Image
import os

def uppercase(string):
    return string[0].upper() + string[1:]

def convert_image(name):
    img = Image.open(f"assets/{name}.png").convert("RGBA") # open image in RGBA mode to get transparency

    img_arr = []

    for i in range(img.size[1]):
        row = []
        for j in range(img.size[0]):
            r, g, b, a = img.getpixel((j, i))
            if a == 0:
                row.append(-1) # if pixel is transparent, append -1
            elif r == 0 and g == 0 and b == 0:
                row.append(1) # if pixel is black, append 1
            else:
                row.append(0) # if pixel is white, append 0
        
        img_arr.append(row) 

    import_text = [ # text to put in the file
        "// generated by compile_images.py",
        "// this file just holds an asset",
        "// it's stored as a 2d array of ints where 0 = white, 1 = black, and -1 = transparent", # i chose this approach because i needed transparency - packing each row into an integer wouldn't allow for this (& would make the dimensions less flexible/more annoying to make flexible)
        "",
        f"class {uppercase(name)} " + "{",
        f"    function Array get() " + "{",
        f"        var Array arr;",
        f"        var Array {", ".join([f"row{i}" for i in range(len(img_arr))])};", # defining all rows
        f"        let arr = Array.new({img.size[1]});"
    ]

    for row in range(len(img_arr)):
        import_text.append(f"        let row{row} = Array.new({img.size[0]});") # initializing each row arr
        import_text.append("        ")
        for col in range(len(img_arr[row])):
            import_text[-1] += f'let row{row}[{col}] = {img_arr[row][col]}; ' # filling in each row arr with the values from the image

    import_text.append("        ")

    for row in range(len(img_arr)):
        import_text[-1] += f"let arr[{row}] = row{row}; " # assigning each row arr to the main array

    import_text.append("        return arr;")
    import_text.append("    }")
    import_text.append("}")

    return "\n".join(import_text)

# loop through all png files in assets folder and convert them to .jack files with the same name containing the jack version of the image
files = os.listdir("assets")
for file in files:
    if file.endswith(".png"):
        name = file.replace(".png", "")
        file_text = convert_image(name)

        with open(f"{uppercase(name)}.jack", "w") as f:
            f.write(file_text)
